### Multi-Device TF-SepNet Evaluation for Official Test Set ###

trainer:
  devices: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: log
      name: tfsepnet_multi_device_evaluation

model:
  class_path: model.lit_asc.LitMultiDeviceInference
  init_args:
    # 
    device_model_paths:
      a: Zhou_XJTLU_task1_1/log_ckpt/device_a-val_acc=0.6761.ckpt
      b: Zhou_XJTLU_task1_1/log_ckpt/device_b-val_acc=0.6036.ckpt
      c: Zhou_XJTLU_task1_1/log_ckpt/device_c-val_acc=0.6191.ckpt
      s1: Zhou_XJTLU_task1_1/log_ckpt/device_s1-val_acc=0.5830.ckpt
      s2: Zhou_XJTLU_task1_1/log_ckpt/device_s2-val_acc=0.5679.ckpt
      s3: Zhou_XJTLU_task1_1/log_ckpt/device_s3-val_acc=0.5991.ckpt
      unknown: Zhou_XJTLU_task1_1/log_ckpt/device_unknown-val_acc=0.5849.ckpt
    #
    backbone_config:
      _target_: model.backbones.TFSepNet
      in_channels: 1
      num_classes: 10
      base_channels: 64
      depth: 17
    
    
    spec_extractor_config:
      _target_: util.CpMel
      n_mels: 512
    
    class_label: scene
    domain_label: device

data:
  class_path: data.data_module.DCASEDataModule
  init_args:
    meta_dir: ../TAU-urban-acoustic-scenes-2025-mobile-evaluation/evaluation_setup
    audio_dir: ../TAU-urban-acoustic-scenes-2025-mobile-evaluation
    batch_size: 64
    num_workers: 4
    pin_memory: true
    sampling_rate: 32000
    predict_subset: test  